import { ItemView, Platform, WorkspaceLeaf, setIcon } from "obsidian";
import type RedBeardDashboard from "./main";
import type { DashboardWidgetDefinition, WidgetLayout } from "./types";

export class DashboardView extends ItemView {
  private editorResizeObserver?:ResizeObserver;
  constructor(leaf:WorkspaceLeaf,private plugin:RedBeardDashboard){super(leaf);}
  getViewType(){return "red-beard-dashboard-view";} getDisplayText(){return "Red-Beard Dashboard";} getIcon(){return "layout-dashboard";}
  async onOpen(){await this.render();}
  async render(){const root=this.containerEl;const mobile=Platform.isMobile||Platform.isMobileApp||Platform.isIosApp;this.editorResizeObserver?.disconnect();this.editorResizeObserver=undefined;root.empty();root.addClass("red-beard-dashboard");root.toggleClass("rbd-is-editing",this.plugin.editing);root.toggleClass("rbd-is-mobile",mobile);root.style.setProperty("--rbd-gap",`${this.plugin.settings.gap}px`);root.style.setProperty("--rbd-padding",`${this.plugin.settings.padding}px`);
    const hero=root.createDiv({cls:"rbd-hero"});hero.createDiv({cls:"rbd-eyebrow",text:"RED-BEARD · PERSONAL KNOWLEDGE VAULT"});hero.createEl("h1",{text:"Welcome home."});hero.createEl("p",{text:new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})});
    const toolbar=root.createDiv({cls:"rbd-toolbar"});this.btn(toolbar,this.plugin.editing?"Done editing":"Edit layout",()=>this.plugin.toggleEditor());if(this.plugin.editing)this.btn(toolbar,"Add widgets",()=>this.plugin.openWidgetManager());this.btn(toolbar,"Refresh",()=>void this.plugin.refreshViews());this.btn(toolbar,"Legacy dashboard",()=>this.plugin.openNote(this.plugin.settings.legacyPath));this.btn(toolbar,"Settings",()=>this.plugin.openSettings());
    const grid=root.createDiv({cls:this.plugin.editing?"rbd-grid rbd-masonry rbd-editing-masonry":"rbd-grid rbd-masonry"});if(mobile){root.style.setProperty("height","auto","important");root.style.setProperty("min-height","100%","important");root.style.setProperty("overflow-y","auto","important");root.style.setProperty("overflow-x","hidden","important");grid.style.setProperty("display","block","important");grid.style.setProperty("position","relative","important");grid.style.setProperty("height","auto","important");grid.style.setProperty("min-height","0","important");grid.style.setProperty("grid-template-columns","none","important");grid.style.setProperty("grid-auto-rows","auto","important");grid.style.setProperty("gap","0","important");}const items=[...this.plugin.widgets.values()].sort((a,b)=>(this.plugin.layout[a.id]?.order??99)-(this.plugin.layout[b.id]?.order??99));
    for(const def of items){const l=this.plugin.layout[def.id]??this.plugin.layoutFor(def);if(l.visible===false)continue;const card=grid.createDiv({cls:"rbd-widget"});card.dataset.widgetId=def.id;if(mobile)card.addClass("rbd-mobile-flow-card");card.style.setProperty("--rbd-x",String(l.x));card.style.setProperty("--rbd-w",String(l.w));card.style.setProperty("--rbd-mobile-w",String(l.mobileW));card.style.setProperty("--rbd-mobile-span",String(Math.max(1,Math.min(12,l.mobileW))));card.style.setProperty("--rbd-h",String(l.h));if(mobile){card.style.setProperty("position","relative","important");card.style.setProperty("display","block","important");card.style.setProperty("float","none","important");card.style.setProperty("left","auto","important");card.style.setProperty("top","auto","important");card.style.setProperty("right","auto","important");card.style.setProperty("bottom","auto","important");card.style.setProperty("width","auto","important");card.style.setProperty("height","auto","important");card.style.setProperty("min-height","0","important");card.style.setProperty("grid-column","auto","important");card.style.setProperty("grid-row","auto","important");card.style.setProperty("transform","none","important");card.style.setProperty("z-index","auto","important");card.style.setProperty("margin-bottom",`${this.plugin.settings.gap}px`);}if(this.plugin.editing&&!l.locked)this.editor(card,def,l);const title=card.createDiv({cls:"rbd-widget-title"});if(def.icon){const icon=title.createSpan({cls:"rbd-widget-icon"});try{setIcon(icon,def.icon);}catch{/* unknown icon: retain the text title */}}title.createEl("span",{text:def.name});if(this.plugin.editing)this.controls(card,l);const body=card.createDiv({cls:"rbd-widget-body"});try{await def.render(this.plugin.context(),body);}catch(e){body.createEl("p",{cls:"rbd-error",text:`Widget unavailable: ${e instanceof Error?e.message:String(e)}`});}}
    if(!items.length)grid.createEl("p",{text:"No widgets are registered."});
    if(!mobile){this.packMasonryLayout(grid);this.editorResizeObserver=new ResizeObserver(()=>this.packMasonryLayout(grid));this.editorResizeObserver.observe(grid);}
    if(this.plugin.editing){const dropGrid=root.createDiv({cls:"rbd-column-drop-grid",attr:{"aria-label":"Drop zones for dashboard columns"}});[1,5,9].forEach(column=>{const zone=dropGrid.createDiv({cls:"rbd-column-drop-zone",text:`Drop in column ${Math.ceil(column/4)}`});zone.dataset.column=String(column);zone.ondragover=e=>{e.preventDefault();zone.addClass("rbd-zone-active")};zone.ondragleave=()=>zone.removeClass("rbd-zone-active");zone.ondrop=e=>{e.preventDefault();zone.removeClass("rbd-zone-active");const from=e.dataTransfer?.getData("text/plain");if(from)void this.plugin.placeWidgetInColumn(from,column);};});}
    if(this.plugin.editing){for(const id of ["quick-actions","modules"]){const card=grid.querySelector<HTMLElement>(`[data-widget-id="${id}"]`);if(card)this.addCardManagerButton(card,id as "quick-actions"|"modules");}}
    root.appendChild(toolbar);
  }
  private addCardManagerButton(card:HTMLElement,kind:"quick-actions"|"modules"){const title=card.querySelector<HTMLElement>(".rbd-widget-title");if(!title)return;const button=title.createEl("button",{cls:"rbd-card-manage-button",text:"Manage"});button.onclick=e=>{e.stopPropagation();this.plugin.openCardManager(kind);};}
  private editor(card:HTMLElement,def:DashboardWidgetDefinition,_l:WidgetLayout){card.addClass("rbd-editing");const handle=card.createDiv({cls:"rbd-drag-handle",text:"⋮⋮ Drag"});handle.draggable=true;handle.ondragstart=e=>{e.dataTransfer?.setData("text/plain",def.id);if(e.dataTransfer)e.dataTransfer.effectAllowed="move";};handle.ondragend=()=>card.removeClass("rbd-dragging");for(const side of ["top","left","right"] as const){const zone=card.createDiv({cls:`rbd-drop-zone rbd-drop-${side}`,text:side==="top"?"Insert above":"",attr:{"aria-label":side==="top"?"Insert above this widget":`Place ${side} of this widget`}});zone.ondragover=e=>{e.preventDefault();zone.addClass("rbd-zone-active");};zone.ondragleave=()=>zone.removeClass("rbd-zone-active");zone.ondrop=e=>{e.preventDefault();zone.removeClass("rbd-zone-active");const from=e.dataTransfer?.getData("text/plain");if(from&&from!==def.id)void this.plugin.moveWidget(from,def.id,side);};}card.ondragover=e=>{e.preventDefault();card.addClass("rbd-drop-target")};card.ondragleave=()=>card.removeClass("rbd-drop-target");card.ondrop=e=>{e.preventDefault();card.classList.remove("rbd-drop-target");const from=e.dataTransfer?.getData("text/plain");if(from&&from!==def.id)void this.plugin.moveWidget(from,def.id,"top");};}
  private controls(parent:HTMLElement,l:WidgetLayout){const c=parent.createDiv({cls:"rbd-widget-controls"});this.field(c,"Width",l.w,1,12,v=>{l.w=v;void this.plugin.saveLayout();});this.field(c,"Mobile",l.mobileW,1,12,v=>{l.mobileW=v;void this.plugin.saveLayout();});this.field(c,"Height",l.h,1,8,v=>{l.h=v;void this.plugin.saveLayout();});this.btn(c,l.locked?"Unlock":"Lock",()=>{l.locked=!l.locked;void this.plugin.saveLayout();});}
  private field(p:HTMLElement,label:string,value:number,min:number,max:number,on:(v:number)=>void){const wrap=p.createDiv({cls:"rbd-field"});wrap.createEl("span",{text:label});const i=wrap.createEl("input",{type:"number",value:String(value),attr:{"aria-label":label,min:String(min),max:String(max)}});i.onchange=()=>on(Math.max(min,Math.min(max,Number(i.value)||value)));}
  private btn(p:HTMLElement,text:string,on:()=>void){const b=p.createEl("button",{text});b.onclick=on;}
  private packMasonryLayout(grid:HTMLElement){if(!grid.isConnected)return;if(Platform.isMobile||this.containerEl.classList.contains("rbd-is-mobile")){grid.style.removeProperty("min-height");return;}const width=grid.clientWidth;if(width<1)return;const gap=Number.parseFloat(getComputedStyle(grid).columnGap)||this.plugin.settings.gap||16;const columns=12;const columnWidth=Math.max(1,(width-gap*(columns-1))/columns);const heights=Array<number>(columns).fill(0);const cards=Array.from(grid.querySelectorAll<HTMLElement>(".rbd-widget"));for(const card of cards){const id=card.dataset.widgetId;if(!id)continue;const l=this.plugin.layout[id]??{x:1,w:4};const x=Math.max(1,Math.min(columns,Math.round(l.x||1)));const w=Math.max(1,Math.min(columns-x+1,Math.round(l.w||4)));const start=x-1;const top=Math.max(...heights.slice(start,start+w),0);const left=start*(columnWidth+gap);const cardWidth=columnWidth*w+gap*(w-1);card.style.setProperty("--rbd-edit-left",`${left}px`);card.style.setProperty("--rbd-edit-top",`${top}px`);card.style.setProperty("--rbd-edit-width",`${cardWidth}px`);const height=card.getBoundingClientRect().height;const bottom=top+height+gap;for(let i=start;i<start+w;i++)heights[i]=bottom;}grid.style.minHeight=`${Math.max(0,(Math.max(...heights,0)-gap))}px`;}
  async onClose(){this.editorResizeObserver?.disconnect();this.editorResizeObserver=undefined;return Promise.resolve();}
}
