import { App, Notice, Plugin, TFile, setIcon } from "obsidian";
import { DashboardView } from "./dashboard";
import { DashboardCardManagerModal } from "./modals";
import { DashboardSettingsTab } from "./settings";
import { DASHBOARD_VIEW, DEFAULT_QUICK_ACTIONS, type DashboardContext, type DashboardModuleDefinition, type DashboardQuickActionDefinition, type DashboardSettings, type DashboardWidgetDefinition, type WidgetLayout } from "./types";
import { defaultLayouts, defaultSettings, normalizeSettings, readManagedLayout, sanitizeLayout, writeLayoutNote, WIDGET_ORDER } from "./utils";

const FALLBACKS:Record<string,string>={"quote-library:open-dashboard":"quote-library-dashboard","scripture-library:open-dashboard":"scripture-library-dashboard","movie-library:open-dashboard":"movie-library-dashboard","study-planner:open-dashboard":"study-planner-dashboard","mens-study-planner:open-dashboard":"mens-study-planner-dashboard","marriage-companion:open-dashboard":"marriage-companion-dashboard","vault-backup:open-dashboard":"vault-backup-dashboard","prayer-library:open-dashboard":"prayer-library-dashboard","journal-companion:open-dashboard":"journal-companion-dashboard"};
function execute(app:App,id:string){const c=(app as App&{commands?:{executeCommandById:(id:string)=>boolean}}).commands;if(c?.executeCommandById(id))return;void app.workspace.getLeaf(true).setViewState({type:FALLBACKS[id]??id,active:true});}
function frontmatter(text:string){const out:Record<string,string|boolean>={};if(!text.startsWith("---\n"))return out;const end=text.indexOf("\n---\n",4);if(end<0)return out;for(const line of text.slice(4,end).split("\n")){const m=/^([\w-]+):\s*(.*)$/.exec(line);if(m){const raw=m[2].replace(/^['"]|['"]$/g,"");out[m[1]]=raw==="true"?true:raw==="false"?false:raw;}}return out;}
function dashboardExcluded(app:App,file:TFile){const value=app.metadataCache.getFileCache(file)?.frontmatter?.dashboard_exclude;return value===true||String(value??"").toLowerCase()==="true";}
type VaultOrganizerProject={name:string;hub:string;files:number;modified:number};
type JournalDailyRecord={file:TFile;date:string};
type BookmarkItem={type?:string;path?:string;items?:BookmarkItem[]};

export default class RedBeardDashboard extends Plugin{
 settings:DashboardSettings=defaultSettings();layout:Record<string,WidgetLayout>=defaultLayouts();widgets=new Map<string,DashboardWidgetDefinition>();modules=new Map<string,DashboardModuleDefinition>();editing=false;private timer?:number;
 async onload(){const d=await this.loadData() as any;this.settings=normalizeSettings(d);const legacy=Boolean(d?.layout&&Object.values(d.layout as Record<string,any>).some(v=>v&&typeof v==="object"&&("sizingMode"in v||"dynamicWidth"in v)));this.layout=legacy?defaultLayouts():sanitizeLayout(d?.layout);if(legacy)await this.saveData({...this.settings,layout:this.layout});await this.loadLayout();this.registerView(DASHBOARD_VIEW,l=>new DashboardView(l,this));this.addSettingTab(new DashboardSettingsTab(this.app,this));this.registerNativeWidgets();this.widgets.delete("quote-of-day");await this.loadMarkdownWidgets();this.ensureKnownIntegrations();this.announceReady();this.addRibbonIcon("layout-dashboard","Open Red-Beard Dashboard",()=>void this.openDashboard());this.addCommand({id:"open-dashboard",name:"Open dashboard",callback:()=>void this.openDashboard()});this.addCommand({id:"edit-layout",name:"Edit dashboard layout",callback:()=>this.toggleEditor()});this.addCommand({id:"refresh",name:"Refresh dashboard",callback:()=>void this.refreshViews()});this.addCommand({id:"open-settings",name:"Open dashboard settings",callback:()=>this.openSettings()});this.addCommand({id:"import-legacy",name:"Import/re-import legacy dashboard",callback:()=>void this.importLegacy()});this.addCommand({id:"reset-layout",name:"Reset dashboard layout",callback:()=>void this.resetLayout()});if(this.settings.dashboard.autoRefreshSeconds>0)this.timer=window.setInterval(()=>void this.refreshViews(),this.settings.dashboard.autoRefreshSeconds*1000);if(this.settings.dashboard.startup)this.app.workspace.onLayoutReady(()=>void this.openDashboard());}
 onunload(){if(this.timer)window.clearInterval(this.timer);this.widgets.forEach(w=>w.cleanup?.());}
 registerWidget(def:DashboardWidgetDefinition){this.widgets.set(def.id,def);if(!this.layout[def.id])this.layout[def.id]=sanitizeLayout({[def.id]:def.defaultLayout})[def.id];void this.refreshViews();return()=>{if(this.widgets.get(def.id)===def){this.widgets.delete(def.id);void this.refreshViews();}};}
 registerModule(def:DashboardModuleDefinition){const previous=this.modules.get(def.id);this.modules.set(def.id,def);if(typeof this.settings.moduleVisibility[def.id]!=="boolean")this.settings.moduleVisibility[def.id]=true;void this.saveSettings();void this.refreshViews();return()=>{if(this.modules.get(def.id)===def){if(previous)this.modules.set(def.id,previous);else this.modules.delete(def.id);void this.refreshViews();}};}
 getQuickActions():DashboardQuickActionDefinition[]{return DEFAULT_QUICK_ACTIONS;}
 getModules():DashboardModuleDefinition[]{return [...this.modules.values()];}
 getWidgets():DashboardWidgetDefinition[]{return [...this.widgets.values()];}
 openCardManager(kind:"quick-actions"|"modules"){new DashboardCardManagerModal(this.app,this,kind).open();}
 openWidgetManager(){new DashboardCardManagerModal(this.app,this,"widgets").open();}
 isModuleEnabled(id:string){return this.settings.moduleVisibility[id]!==false;}
 isWidgetVisible(id:string){return this.layout[id]?.visible!==false;}
 layoutFor(def:DashboardWidgetDefinition){return this.layout[def.id]??defaultLayouts()[def.id]??{x:1,w:4,mobileW:12,h:1,order:99,visible:true,locked:false};}
 context():DashboardContext{return{app:this.app,vault:this.app.vault,settings:this.settings,layout:this.layout,refresh:()=>this.refreshViews(),openNote:p=>this.openNote(p),notice:m=>new Notice(m)};}
 async saveSettings(){await this.saveData({...this.settings,layout:this.layout});}
 async saveLayout(){await this.saveSettings();try{await writeLayoutNote(this.app.vault,this.settings,this.layout);}catch(e){new Notice(`Could not save layout: ${e instanceof Error?e.message:String(e)}`);}await this.refreshViews();}
 async resetLayout(){this.layout=defaultLayouts();await this.saveLayout();new Notice("Dashboard layout reset.");}
 async openDashboard(){this.ensureKnownIntegrations();const leaf=this.app.workspace.getLeaf(true);await leaf.setViewState({type:DASHBOARD_VIEW,active:true});this.app.workspace.revealLeaf(leaf);await this.refreshViews();}
 openNote(path:string){void this.app.workspace.openLinkText(path.replace(/\.md$/i,""),"",false);}
 openSettings(){const s=(this.app as any).setting;s?.open?.();window.setTimeout(()=>s?.openTabById?.(this.manifest.id),100);}
 toggleEditor(){this.editing=!this.editing;void this.refreshViews();}
 announceReady(){window.dispatchEvent(new CustomEvent("red-beard-dashboard-ready"));}
 async refreshViews(){for(const l of this.app.workspace.getLeavesOfType(DASHBOARD_VIEW))if(l.view instanceof DashboardView)try{await(l.view as DashboardView).render();}catch(e){new Notice(`Dashboard refresh failed: ${e instanceof Error?e.message:String(e)}`);}}
 ensureKnownIntegrations(){const plugins=(this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins;if(plugins?.getPlugin?.("quote-library")){if(!this.modules.has("quote-library"))this.registerModule({id:"quote-library",name:"Quote Library",command:"quote-library:open-dashboard",icon:"quote",description:"Browse and manage saved quotes.",order:10});this.registerFallbackQuoteWidgets();}if(plugins?.getPlugin?.("prayer-library")){if(!this.modules.has("prayer-library"))this.registerModule({id:"prayer-library",name:"Prayer Library",command:"prayer-library:open-dashboard",icon:"heart",description:"Daily prayer rotation and schedules.",order:20});this.registerFallbackPrayerWidget();}if(plugins?.getPlugin?.("scripture-library")){if(!this.modules.has("scripture-library"))this.registerModule({id:"scripture-library",name:"Scripture Library",command:"scripture-library:open-dashboard",icon:"book-open",description:"Saved passages, topics, and daily Scripture.",order:30});this.registerFallbackScriptureWidget();}}
 private registerFallbackQuoteWidgets(){const quoteFiles=()=>this.app.vault.getMarkdownFiles().map(file=>({file,meta:this.app.metadataCache.getFileCache(file)?.frontmatter??{}})).filter(item=>typeof item.meta.quote_text==="string"&&!Boolean(item.meta.quote_archive));const render=(kind:"daily"|"pinned"|"recent",container:HTMLElement)=>{const candidates=quoteFiles();const pool=kind==="pinned"?candidates.filter(item=>item.meta.quote_pin===true||String(item.meta.quote_pin).toLowerCase()==="true"):kind==="recent"?candidates.sort((a,b)=>b.file.stat.mtime-a.file.stat.mtime):candidates;const item=(pool.length?pool:candidates)[kind==="daily"&&pool.length?Math.floor(Date.now()/86400000)%pool.length:0];if(!item){container.createDiv({cls:"rbd-empty-state",text:"No quotes available yet."});return;}const text=String(item.meta.quote_text).replace(/^['"]|['"]$/g,"");container.createEl("blockquote",{cls:"rbd-quote-text",text});const author=String(item.meta.quote_author??"").trim(),source=String(item.meta.quote_source??"").trim();if(author||source)container.createDiv({cls:"rbd-quote-footer",text:[author?`— ${author}`:"",source].filter(Boolean).join(" · ")});const button=container.createEl("button",{text:"Open quote"});button.onclick=()=>this.openNote(item.file.path);};const definitions:[string,string,string,string,Partial<WidgetLayout>][]=[["quote-library.quote-of-day","Quote of the Day","quote","The latest saved quote.",{x:1,w:4,mobileW:12,h:2,order:2}],["quote-library.pinned","Pinned Quotes","pin","Pinned saved quotes.",{x:1,w:4,mobileW:12,h:2,order:30}],["quote-library.recent","Recent Quotes","clock-3","Recently added quotes.",{x:1,w:4,mobileW:12,h:2,order:31}]];for(const [id,name,icon,description,defaultLayout] of definitions)if(!this.widgets.has(id))this.registerWidget({id,name,icon,description,defaultLayout,render:(_,container)=>render(id.endsWith("quote-of-day")?"daily":id.endsWith("pinned")?"pinned":"recent",container)});}
 private registerFallbackPrayerWidget(){const id="prayer-library/overview";if(this.widgets.has(id))return;this.registerWidget({id,name:"Prayer Library",icon:"heart",description:"Today’s prayers with quick mark-prayed actions.",defaultLayout:{x:9,w:4,mobileW:12,h:3,order:32},render:async(_,container)=>{container.empty();const plugin=(((this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins?.getPlugin?.("prayer-library")) as {getDailyPrayers?:(date?:string)=>Promise<any[]>|any[];getPrayers?:()=>any[];markPrayed?:(p:any,date:string)=>Promise<void>;settings?:{categories?:Array<{name:string;count:number;archived?:boolean}>}})||{};const date=new Date().toISOString().slice(0,10);let items=plugin.getDailyPrayers?await plugin.getDailyPrayers(date):[];if(!items.length&&plugin.getPrayers){const active=plugin.getPrayers().filter((p:any)=>p.status==="active");const chosen:any[]=[];const add=(p:any)=>{if(!chosen.some(item=>item.id===p.id))chosen.push(p)};const dayNames=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"];const matches=(schedule:any)=>{if(!schedule||typeof schedule!=="object")return false;const d=new Date(`${date}T12:00:00`);if(schedule.frequency==="dates")return Array.isArray(schedule.dates)&&schedule.dates.includes(date);if(schedule.frequency==="monthly")return d.getDate()===Number(schedule.day);return Array.isArray(schedule.weekdays)&&schedule.weekdays.map((value:any)=>String(value).toLowerCase()).includes(dayNames[d.getDay()])};active.filter((p:any)=>Array.isArray(p.schedule)&&p.schedule.some(matches)).forEach(add);(plugin.settings?.categories||[]).filter(c=>!c.archived).forEach(c=>active.filter((p:any)=>p.category===c.name&&p.rotation&&!chosen.some(item=>item.id===p.id)).sort((a:any,b:any)=>((a.prayed||[]).filter((x:string)=>x<=date).sort().pop()||"0000").localeCompare((b.prayed||[]).filter((x:string)=>x<=date).sort().pop()||"0000")||Number(a.priority||1)-Number(b.priority||1)||String(a.id).localeCompare(String(b.id))).slice(0,Math.max(0,Number(c.count)||0)).forEach(add));items=chosen;}container.createEl("p",{cls:"rbd-muted",text:items.length?`${date} · ${items.length} ${items.length===1?"prayer":"prayers"}:`:`No prayers scheduled for today.`});const list=container.createDiv({cls:"rbd-prayer-list"});items.forEach((p:any)=>{const row=list.createDiv({cls:"rbd-prayer-row"}),copy=row.createDiv({cls:"rbd-prayer-copy"});copy.createEl("strong",{text:String(p.title||p.id||"Prayer")});const prayed=Array.isArray(p.prayed)&&p.prayed.includes(date),button=row.createEl("button",{text:prayed?"Prayed ✓":"Mark prayed"});button.disabled=prayed;button.onclick=async()=>{if(plugin.markPrayed){await plugin.markPrayed(p,date);button.setText("Prayed ✓");button.disabled=true;}};});const open=container.createEl("button",{text:"Open Prayer Library"});open.onclick=()=>execute(this.app,"prayer-library:open-dashboard");}});}
 private registerFallbackScriptureWidget(){const id="scripture-library/passage-of-day";if(this.widgets.has(id))return;this.registerWidget({id,name:"Scripture of the Day",icon:"book-open",description:"One saved passage selected for today.",defaultLayout:{x:5,w:4,mobileW:12,h:3,order:33},render:async(_,container)=>{container.empty();const plugin=((this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins?.getPlugin?.("scripture-library")) as {getPassageOfDay?:(date?:string)=>Promise<any>}|undefined;const date=new Date().toISOString().slice(0,10);let passage=await plugin?.getPassageOfDay?.(date);if(!passage){const files=this.app.vault.getMarkdownFiles().map(file=>({file,meta:this.app.metadataCache.getFileCache(file)?.frontmatter??{}})).filter(x=>String(x.meta.type||"")==="scripture-library-passage");if(files.length){let hash=0;for(const char of date)hash=(hash*31+char.charCodeAt(0))>>>0;const item=files.sort((a,b)=>a.file.path.localeCompare(b.file.path))[hash%files.length];passage={path:item.file.path,reference:String(item.meta.reference||item.file.basename),translation:String(item.meta.translation||""),text:String(item.meta.passage_text||item.meta.text||"")};}}if(!passage){container.createDiv({cls:"rbd-empty-state",text:"Save a Scripture passage to begin."});return;}const card=container.createDiv({cls:"rbd-scripture-card"}),heading=card.createDiv({cls:"rbd-scripture-heading"});heading.createEl("strong",{text:String(passage.reference||"Scripture")});if(passage.translation)heading.createEl("span",{text:String(passage.translation),cls:"rbd-badge"});card.createEl("blockquote",{text:String(passage.text||"(No passage text yet)")});const details=[passage.book,passage.category].filter(Boolean).join(" · ");if(details)card.createEl("p",{text:details,cls:"rbd-muted"});const open=card.createEl("button",{text:"Open passage"});open.onclick=()=>this.openNote(String(passage.path));}});}
 async moveWidget(fromId:string,toId:string,side:"top"|"bottom"|"left"|"right"){const from=this.layout[fromId],to=this.layout[toId];if(!from||!to)return;const targetX=side==="top"||side==="bottom"?to.x:side==="left"?to.x-from.w:to.x+to.w;from.x=Math.max(1,Math.min(13-from.w,targetX));/* Keep horizontal drops adjacent in the saved sequence as well as in the selected column.  The masonry packer follows order, so changing only x can make a right/left drop appear much later in the page. */if(side==="top"||side==="left")from.order=(to.order??99)-0.25;else if(side==="bottom"||side==="right")from.order=(to.order??99)+0.25;await this.saveLayout();}
 async placeWidgetInColumn(id:string,column:number){const from=this.layout[id];if(!from)return;from.x=Math.max(1,Math.min(13-from.w,column));const orders=Object.values(this.layout).map(l=>l.order).filter(v=>Number.isFinite(v));from.order=(orders.length?Math.max(...orders):0)+0.25;await this.saveLayout();}
 async importLegacy(){const f=this.app.vault.getAbstractFileByPath(this.settings.legacyPath);if(!(f instanceof TFile)){new Notice(`Legacy dashboard not found: ${this.settings.legacyPath}`);return;}const text=await this.app.vault.read(f);WIDGET_ORDER.forEach((id,i)=>{if(this.layout[id]&&text.toLowerCase().includes(id.replace(/-/g," ")))this.layout[id].order=i;});await this.saveLayout();new Notice("Legacy dashboard imported; original note preserved.");}
 private async loadLayout(){const f=this.app.vault.getAbstractFileByPath(this.settings.dashboardPath);if(f instanceof TFile){const l=readManagedLayout(await this.app.vault.cachedRead(f));if(l)this.layout=sanitizeLayout(l,this.layout);}}
 private registerNativeWidgets(){const actions=this.getQuickActions();this.registerWidget({id:"quick-actions",name:"Quick Actions",icon:"zap",defaultLayout:{x:1,w:12,mobileW:12,h:1,order:0},render:(_,c)=>{const group=c.createDiv({cls:"rbd-action-grid"});actions.filter(a=>this.settings.quickActionVisibility[a.id]!==false).sort((a,b)=>(this.settings.quickActionOrder[a.id]??99)-(this.settings.quickActionOrder[b.id]??99)).forEach((action,index)=>{const style=this.settings.quickActionStyle[action.id]??(index===0?"blue":"default");const b=group.createEl("button",{text:action.name,cls:`rbd-action-button rbd-highlight-${style}`});b.onclick=()=>execute(this.app,action.command);});}});this.registerWidget({id:"modules",name:"Modules",icon:"layout-grid",defaultLayout:{x:1,w:12,mobileW:12,h:1,order:1},render:(_,c)=>{const modules=[...this.modules.values()].filter(m=>this.isModuleEnabled(m.id)).sort((a,b)=>(this.settings.moduleOrder[a.id]??a.order??99)-(this.settings.moduleOrder[b.id]??b.order??99)||a.name.localeCompare(b.name));if(!modules.length){const empty=c.createDiv({cls:"rbd-empty-state"});empty.createEl("p",{text:"No connected modules are available yet."});empty.createEl("small",{text:"Enable an add-on, then reopen or refresh this dashboard."});return;}const group=c.createDiv({cls:"rbd-module-grid"});modules.forEach(m=>{const hasCustomFlavor=Object.prototype.hasOwnProperty.call(this.settings.moduleFlavor,m.id),flavor=hasCustomFlavor?this.settings.moduleFlavor[m.id].trim():m.description||"",style=this.settings.moduleStyle[m.id]??"default",b=group.createEl("button",{cls:`rbd-module-button rbd-highlight-${style}`,attr:{"aria-label":flavor?`${m.name}: ${flavor}`:m.name,"title":flavor||m.name}});if(m.icon){const icon=b.createSpan({cls:"rbd-module-icon"});try{setIcon(icon,m.icon);}catch{icon.setText("•");}}const copy=b.createSpan({cls:"rbd-module-copy"});copy.createSpan({cls:"rbd-module-label",text:m.name});if(flavor)copy.createSpan({cls:"rbd-module-description",text:flavor});b.onclick=()=>execute(this.app,m.command);});}});this.registerWidget({id:"quote-of-day",name:"Quote of the Day",icon:"quote",defaultLayout:{x:1,w:4,mobileW:12,h:2,order:2},render:(_,c)=>this.renderQuote(c)});this.listWidget("recently-changed","Recently Changed",f=>!dashboardExcluded(this.app,f),8,{x:5,w:4,order:3});this.registerFavoriteWidget();this.registerActiveProjectsWidget();this.registerRecentJournalWidget();this.registerWidget({id:"vault-pulse",name:"Vault Pulse",icon:"activity",defaultLayout:{x:9,w:4,order:7},render:(_,c)=>{const fs=this.app.vault.getFiles(),day=Date.now()-86400000;c.createDiv({cls:"rbd-pulse-metric",text:`${fs.length} files`});c.createEl("p",{cls:"rbd-muted",text:`${new Set(fs.map(f=>f.parent?.path)).size} folders · ${fs.filter(f=>f.stat.mtime>day).length} changed today`});}});}
 private registerFavoriteWidget(){this.registerWidget({id:"favorites",name:"Favorites",icon:"star",defaultLayout:{x:9,w:4,order:4},render:(_,c)=>this.renderFavorites(c)});}
 private renderFavorites(c:HTMLElement){const paths=this.bookmarkPaths();let files=(paths.length?paths.map(path=>this.app.vault.getAbstractFileByPath(path)).filter((file):file is TFile=>file instanceof TFile&&file.extension.toLowerCase()==="md"&&!dashboardExcluded(this.app,file)):this.app.vault.getMarkdownFiles().filter(file=>!dashboardExcluded(this.app,file)&&this.explicitFavorite(file)).sort((a,b)=>b.stat.mtime-a.stat.mtime));if(!files.length){c.createDiv({cls:"rbd-empty-state",text:"No bookmarked pages yet."});return;}const list=c.createEl("ul",{cls:"rbd-link-list"});files.slice(0,8).forEach(file=>{const li=list.createEl("li",{cls:"rbd-link-row"}),a=li.createEl("a",{text:file.basename});a.onclick=()=>this.openNote(file.path);});}
 private bookmarkPaths():string[]{const app=this.app as App&{internalPlugins?:{getPluginById?:(id:string)=>unknown}};const internal=app.internalPlugins?.getPluginById?.("bookmarks") as {instance?:unknown;items?:unknown}|undefined;const instance=internal?.instance as {items?:unknown;data?:{items?:unknown}}|undefined;const raw=instance?.items??instance?.data?.items??internal?.items;const paths:string[]=[];const visit=(value:unknown):void=>{if(Array.isArray(value)){value.forEach(visit);return;}if(!value||typeof value!=="object")return;const item=value as BookmarkItem;if(item.type==="file"&&typeof item.path==="string"&&!paths.includes(item.path))paths.push(item.path);if(Array.isArray(item.items))item.items.forEach(visit);};visit(raw);return paths;}
 private explicitFavorite(file:TFile):boolean{const fm=this.app.metadataCache.getFileCache(file)?.frontmatter as Record<string,unknown>|undefined;const value=fm?.favorite??fm?.favourite;const tags=Array.isArray(fm?.tags)?fm.tags.map(String):typeof fm?.tags==="string"?String(fm.tags).split(/[\s,]+/):[];return value===true||String(value??"").toLowerCase()==="true"||tags.some(tag=>tag.replace(/^#/,'').toLowerCase()==="favorite");}
 private registerActiveProjectsWidget(){this.registerWidget({id:"active-projects",name:"Active Projects",icon:"folder-kanban",defaultLayout:{x:1,w:4,order:5},render:(_,c)=>this.renderActiveProjects(c)});}
 private renderActiveProjects(c:HTMLElement){const organizer=this.vaultOrganizer();let projects:VaultOrganizerProject[]=[];try{projects=organizer?.repository?.getProjectFolders?.()??[]}catch{/* fall through to the portable frontmatter/root adapter */}if(!projects.length)projects=this.fallbackProjectFolders(organizer);if(!projects.length){c.createDiv({cls:"rbd-empty-state",text:"No Vault Organizer projects yet."});return;}const list=c.createEl("ul",{cls:"rbd-link-list"});projects.slice(0,8).forEach(project=>{const li=list.createEl("li",{cls:"rbd-link-row"}),a=li.createEl("a",{text:project.name});a.onclick=()=>{if(organizer?.openProject)organizer.openProject.call(organizer,project);else this.openNote(project.hub);};li.createEl("span",{cls:"rbd-muted",text:`${project.files} file${project.files===1?"":"s"}`});});}
 private vaultOrganizer(){const plugins=(this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins;return plugins?.getPlugin?.("vault-organizer") as {repository?:{getProjectFolders?:()=>VaultOrganizerProject[]};openProject?:(project:VaultOrganizerProject)=>void;settings?:{projects?:{root?:{path?:string}}}}|undefined;}
 private fallbackProjectFolders(organizer?:ReturnType<RedBeardDashboard["vaultOrganizer"]>):VaultOrganizerProject[]{const root=String(organizer?.settings?.projects?.root?.path??"").replace(/\/+$/g,"");const files=this.app.vault.getMarkdownFiles().filter(file=>!dashboardExcluded(this.app,file));const marked=files.filter(file=>{const fm=this.app.metadataCache.getFileCache(file)?.frontmatter as Record<string,unknown>|undefined;const owner=fm?.vault_organizer as Record<string,unknown>|undefined;return owner?.kind==="project"||fm?.type==="project";});const source=root?files.filter(file=>file.path===root||file.path.startsWith(`${root}/`)):marked;const groups=new Map<string,VaultOrganizerProject>();for(const file of source){const relative=root&&file.path.startsWith(`${root}/`)?file.path.slice(root.length+1):file.path;const parts=relative.split("/");const isMarked=marked.includes(file);if(parts.length<2&&!isMarked)continue;const name=root&&parts.length>=2?parts[0]:file.parent?.name??file.basename;const existing=groups.get(name)??{name,hub:file.path,files:0,modified:0};existing.files++;existing.modified=Math.max(existing.modified,file.stat.mtime);if(file.parent?.name===name&&file.path.split("/").length<=existing.hub.split("/").length)existing.hub=file.path;groups.set(name,existing);}return [...groups.values()].sort((a,b)=>b.modified-a.modified);}
 private registerRecentJournalWidget(){this.registerWidget({id:"recent-journal",name:"Recent Journal",icon:"book-open",defaultLayout:{x:5,w:4,order:6},render:async(_,c)=>this.renderRecentJournal(c)});}
 private async renderRecentJournal(c:HTMLElement){const journal=this.journalCompanion();let records:JournalDailyRecord[]=[];try{records=journal?.repository?.getRecent?await journal.repository.getRecent(7):[]}catch{/* use the compatibility adapter below */}if(!records.length)records=this.fallbackJournalRecords(journal);if(!records.length){c.createDiv({cls:"rbd-empty-state",text:"No Journal Companion entries yet."});return;}const list=c.createEl("ul",{cls:"rbd-link-list"});records.slice(0,7).forEach(record=>{const li=list.createEl("li",{cls:"rbd-link-row"}),a=li.createEl("a",{text:record.date||record.file.basename});a.onclick=()=>this.openNote(record.file.path);});}
 private journalCompanion(){const plugins=(this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins;return plugins?.getPlugin?.("journal-companion") as {repository?:{getRecent?:(limit:number)=>Promise<JournalDailyRecord[]>};settings?:{folders?:{daily?:string};legacySourceFolder?:string}}|undefined;}
 private fallbackJournalRecords(journal?:ReturnType<RedBeardDashboard["journalCompanion"]>):JournalDailyRecord[]{const daily=String(journal?.settings?.folders?.daily??"Journal Companion/Daily").replace(/\/+$/g,"");const legacy=String(journal?.settings?.legacySourceFolder??"Journal").replace(/\/+$/g,"");const month:Record<string,string>={jan:"01",feb:"02",mar:"03",apr:"04",may:"05",jun:"06",jul:"07",aug:"08",sep:"09",oct:"10",nov:"11",dec:"12"};const extractDate=(file:TFile,fm:Record<string,unknown>|undefined):string=>{const value=String(fm?.date??"");if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const match=/(\d{4})[-_]([A-Za-z]{3}|\d{2})[-_](\d{2})/.exec(value||file.basename);if(!match)return value;const m=/^\d{2}$/.test(match[2])?match[2]:month[match[2].toLowerCase()];return m?`${match[1]}-${m}-${match[3]}`:value;};const under=(path:string,root:string)=>Boolean(root)&&(path===root||path.startsWith(`${root}/`));return this.app.vault.getMarkdownFiles().filter(file=>!dashboardExcluded(this.app,file)).map(file=>{const fm=this.app.metadataCache.getFileCache(file)?.frontmatter as Record<string,unknown>|undefined;const type=String(fm?.type??"");const tags=Array.isArray(fm?.tags)?fm.tags.map(String).map(tag=>tag.replace(/^#/,'').toLowerCase()):[];const isTyped=type==="journal-companion-daily";const inDaily=under(file.path,daily);const inLegacy=under(file.path,legacy);const looksDated=/\d{4}[-_](?:\d{2}|[A-Za-z]{3})[-_]\d{2}/i.test(file.basename);const isLegacy=(inLegacy&&(String(fm?.category??"").toLowerCase()==="daily_note"||tags.includes("journal")||looksDated));if(file.basename.toLowerCase()==="journal"&&!isTyped&&!inDaily)return null;if(!isTyped&&!inDaily&&!isLegacy)return null;return{file,date:extractDate(file,fm)}}).filter((record):record is JournalDailyRecord=>Boolean(record)).sort((a,b)=>b.date.localeCompare(a.date)||b.file.stat.mtime-a.file.stat.mtime).slice(0,7);}
 private async renderQuote(c:HTMLElement){const candidates=this.app.vault.getMarkdownFiles().map(file=>({file,meta:this.app.metadataCache.getFileCache(file)?.frontmatter??{}})).filter(x=>typeof x.meta.quote_text==="string"&&!Boolean(x.meta.quote_archive));if(!candidates.length){c.createDiv({cls:"rbd-empty-state",text:"Your saved quotes will appear here."});return;}const pinned=candidates.filter(x=>x.meta.quote_pin===true||String(x.meta.quote_pin).toLowerCase()==="true"),pool=pinned.length?pinned:candidates,item=pool[Math.floor(Date.now()/86400000)%pool.length],text=String(item.meta.quote_text).replace(/^['"]|['"]$/g,"");const card=c.createDiv({cls:"rbd-quote-card rbd-quote-card-link",attr:{role:"link",tabindex:"0","aria-label":`Open quote${item.meta.quote_author?` by ${item.meta.quote_author}`:""}`}});card.createEl("blockquote",{cls:"rbd-quote-text",text});const author=String(item.meta.quote_author||"").trim(),source=String(item.meta.quote_source||"").trim();if(author||source){const footer=card.createDiv({cls:"rbd-quote-footer"});if(author)footer.createSpan({cls:"rbd-quote-author",text:`— ${author}`});if(source)footer.createSpan({cls:"rbd-quote-source",text:source});}const open=()=>{if(!this.editing)this.openNote(item.file.path);};card.onclick=open;card.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}};}
 private listWidget(id:string,name:string,filter:(f:any)=>boolean,limit:number,layout:Partial<WidgetLayout>){this.registerWidget({id,name,icon:id==="recently-changed"?"clock-3":id==="favorites"?"star":id==="active-projects"?"folder-kanban":id==="recent-journal"?"book-open":"list",defaultLayout:layout,render:(_,c)=>{const files=this.app.vault.getMarkdownFiles().filter(filter).sort((a,b)=>b.stat.mtime-a.stat.mtime).slice(0,limit);if(!files.length){c.createDiv({cls:"rbd-empty-state",text:"Nothing here yet."});return;}const list=c.createEl("ul",{cls:"rbd-link-list"});files.forEach(f=>{const li=list.createEl("li",{cls:"rbd-link-row"}),a=li.createEl("a",{text:f.basename});a.onclick=()=>this.openNote(f.path);});}});}
 private async loadMarkdownWidgets(){const files=this.app.vault.getMarkdownFiles().filter(f=>f.path.startsWith(`${this.settings.widgetFolder}/`));for(const f of files){const fm=frontmatter(await this.app.vault.cachedRead(f));if(fm.type!=="dashboard-widget"||fm.enabled===false)continue;const id=String(fm.widget_id||f.basename);this.registerWidget({id,name:String(fm.title||f.basename),defaultLayout:{w:4,order:99},render:(_,c)=>{c.createEl("p",{text:`Widget definition: ${f.basename}`});}});}}
}
