import { App, Notice, Plugin, TFile, setIcon } from "obsidian";
import { DashboardView } from "./dashboard";
import { DashboardCardManagerModal } from "./modals";
import { DashboardSettingsTab } from "./settings";
import { DASHBOARD_VIEW, DEFAULT_QUICK_ACTIONS, type DashboardContext, type DashboardModuleDefinition, type DashboardQuickActionDefinition, type DashboardSettings, type DashboardWidgetDefinition, type WidgetLayout } from "./types";
import { defaultLayouts, defaultSettings, normalizeSettings, readManagedLayout, sanitizeLayout, writeLayoutNote, WIDGET_ORDER } from "./utils";

const FALLBACKS:Record<string,string>={"quote-library:open-dashboard":"quote-library-dashboard","scripture-library:open-dashboard":"scripture-library-dashboard","movie-library:open-dashboard":"movie-library-dashboard","study-planner:open-dashboard":"study-planner-dashboard","mens-study-planner:open-dashboard":"mens-study-planner-dashboard","marriage-companion:open-dashboard":"marriage-companion-dashboard","vault-backup:open-dashboard":"vault-backup-dashboard","prayer-library:open-dashboard":"prayer-library-dashboard","journal-companion:open-dashboard":"journal-companion-dashboard"};
function execute(app:App,id:string){const c=(app as App&{commands?:{executeCommandById:(id:string)=>boolean}}).commands;if(c?.executeCommandById(id))return;void app.workspace.getLeaf(true).setViewState({type:FALLBACKS[id]??id,active:true});}
function frontmatter(text:string){const out:Record<string,string|boolean>={};if(!text.startsWith("---\n"))return out;const end=text.indexOf("\n---\n",4);if(end<0)return out;for(const line of text.slice(4,end).split("\n")){const m=/^([\w-]+):\s*(.*)$/.exec(line);if(m){const raw=m[2].replace(/^['"]|['"]$/g,"");out[m[1]]=raw==="true"?true:raw==="false"?false:raw;}}return out;}
function dashboardExcluded(app:App,file:TFile){const value=app.metadataCache.getFileCache(file)?.frontmatter?.dashboard_exclude;return value===true||String(value??"").toLowerCase()==="true";}

export default class RedBeardDashboard extends Plugin{
 settings:DashboardSettings=defaultSettings();layout:Record<string,WidgetLayout>=defaultLayouts();widgets=new Map<string,DashboardWidgetDefinition>();modules=new Map<string,DashboardModuleDefinition>();editing=false;private timer?:number;
 async onload(){const d=await this.loadData() as any;this.settings=normalizeSettings(d);const legacy=Boolean(d?.layout&&Object.values(d.layout as Record<string,any>).some(v=>v&&typeof v==="object"&&("sizingMode"in v||"dynamicWidth"in v)));this.layout=legacy?defaultLayouts():sanitizeLayout(d?.layout);if(legacy)await this.saveData({...this.settings,layout:this.layout});await this.loadLayout();this.registerView(DASHBOARD_VIEW,l=>new DashboardView(l,this));this.addSettingTab(new DashboardSettingsTab(this.app,this));this.registerNativeWidgets();await this.loadMarkdownWidgets();this.ensureKnownIntegrations();this.announceReady();this.addRibbonIcon("layout-dashboard","Open Red-Beard Dashboard",()=>void this.openDashboard());this.addCommand({id:"open-dashboard",name:"Open dashboard",callback:()=>void this.openDashboard()});this.addCommand({id:"edit-layout",name:"Edit dashboard layout",callback:()=>this.toggleEditor()});this.addCommand({id:"refresh",name:"Refresh dashboard",callback:()=>void this.refreshViews()});this.addCommand({id:"open-settings",name:"Open dashboard settings",callback:()=>this.openSettings()});this.addCommand({id:"import-legacy",name:"Import/re-import legacy dashboard",callback:()=>void this.importLegacy()});this.addCommand({id:"reset-layout",name:"Reset dashboard layout",callback:()=>void this.resetLayout()});if(this.settings.dashboard.autoRefreshSeconds>0)this.timer=window.setInterval(()=>void this.refreshViews(),this.settings.dashboard.autoRefreshSeconds*1000);if(this.settings.dashboard.startup)this.app.workspace.onLayoutReady(()=>void this.openDashboard());}
 onunload(){if(this.timer)window.clearInterval(this.timer);this.widgets.forEach(w=>w.cleanup?.());}
 registerWidget(def:DashboardWidgetDefinition){this.widgets.set(def.id,def);if(!this.layout[def.id])this.layout[def.id]=sanitizeLayout({[def.id]:def.defaultLayout})[def.id];void this.refreshViews();return()=>{if(this.widgets.get(def.id)===def){this.widgets.delete(def.id);void this.refreshViews();}};}
 registerModule(def:DashboardModuleDefinition){const previous=this.modules.get(def.id);this.modules.set(def.id,def);if(typeof this.settings.moduleVisibility[def.id]!=="boolean")this.settings.moduleVisibility[def.id]=true;void this.saveSettings();void this.refreshViews();return()=>{if(this.modules.get(def.id)===def){if(previous)this.modules.set(def.id,previous);else this.modules.delete(def.id);void this.refreshViews();}};}
 getQuickActions():DashboardQuickActionDefinition[]{return DEFAULT_QUICK_ACTIONS;}
 getModules():DashboardModuleDefinition[]{return [...this.modules.values()];}
 openCardManager(kind:"quick-actions"|"modules"){new DashboardCardManagerModal(this.app,this,kind).open();}
 isModuleEnabled(id:string){return this.settings.moduleVisibility[id]!==false;}
 layoutFor(def:DashboardWidgetDefinition){return this.layout[def.id]??defaultLayouts()[def.id]??{x:1,w:4,mobileW:12,h:1,order:99,visible:true,locked:false};}
 context():DashboardContext{return{app:this.app,vault:this.app.vault,settings:this.settings,layout:this.layout,refresh:()=>this.refreshViews(),openNote:p=>this.openNote(p),notice:m=>new Notice(m)};}
 async saveSettings(){await this.saveData({...this.settings,layout:this.layout});}
 async saveLayout(){await this.saveSettings();try{await writeLayoutNote(this.app.vault,this.settings,this.layout);}catch(e){new Notice(`Could not save layout: ${e instanceof Error?e.message:String(e)}`);}await this.refreshViews();}
 async resetLayout(){this.layout=defaultLayouts();await this.saveLayout();new Notice("Dashboard layout reset.");}
 async openDashboard(){this.ensureKnownIntegrations();const leaf=this.app.workspace.getLeaf(true);await leaf.setViewState({type:DASHBOARD_VIEW,active:true});this.app.workspace.revealLeaf(leaf);await this.refreshViews();}
 openNote(path:string){void this.app.workspace.openLinkText(path.replace(/\.md$/i,""),"",false);}
 openSettings(){const s=(this.app as any).setting;s?.open?.();window.setTimeout(()=>s?.openTabById?.(this.manifest.id),100);}
 toggleEditor(){this.editing=!this.editing;void this.refreshViews();}
 announceReady(){window.dispatchEvent(new CustomEvent("red-beard-dashboard-ready"));}
 async refreshViews(){for(const l of this.app.workspace.getLeavesOfType(DASHBOARD_VIEW))if(l.view instanceof DashboardView)try{await(l.view as DashboardView).render();}catch(e){new Notice(`Dashboard refresh failed: ${e instanceof Error?e.message:String(e)}`);}}
 ensureKnownIntegrations(){const plugins=(this.app as App&{plugins?:{getPlugin?:(id:string)=>unknown}}).plugins;if(plugins?.getPlugin?.("quote-library")){if(!this.modules.has("quote-library"))this.registerModule({id:"quote-library",name:"Quote Library",command:"quote-library:open-dashboard",icon:"quote",description:"Browse and manage saved quotes.",order:10});this.registerFallbackQuoteWidgets();}if(plugins?.getPlugin?.("prayer-library")){if(!this.modules.has("prayer-library"))this.registerModule({id:"prayer-library",name:"Prayer Library",command:"prayer-library:open-dashboard",icon:"heart",description:"Daily prayer rotation and schedules.",order:20});this.registerFallbackPrayerWidget();}}
 private registerFallbackQuoteWidgets(){const quoteFiles=()=>this.app.vault.getMarkdownFiles().map(file=>({file,meta:this.app.metadataCache.getFileCache(file)?.frontmatter??{}})).filter(item=>typeof item.meta.quote_text==="string"&&!Boolean(item.meta.quote_archive));const render=(kind:"daily"|"pinned"|"recent",container:HTMLElement)=>{const candidates=quoteFiles();const pool=kind==="pinned"?candidates.filter(item=>item.meta.quote_pin===true||String(item.meta.quote_pin).toLowerCase()==="true"):kind==="recent"?candidates.sort((a,b)=>b.file.stat.mtime-a.file.stat.mtime):candidates;const item=(pool.length?pool:candidates)[kind==="daily"&&pool.length?Math.floor(Date.now()/86400000)%pool.length:0];if(!item){container.createDiv({cls:"rbd-empty-state",text:"No quotes available yet."});return;}const text=String(item.meta.quote_text).replace(/^['"]|['"]$/g,"");container.createEl("blockquote",{cls:"rbd-quote-text",text});const author=String(item.meta.quote_author??"").trim(),source=String(item.meta.quote_source??"").trim();if(author||source)container.createDiv({cls:"rbd-quote-footer",text:[author?`— ${author}`:"",source].filter(Boolean).join(" · ")});const button=container.createEl("button",{text:"Open quote"});button.onclick=()=>this.openNote(item.file.path);};const definitions:[string,string,string,string,Partial<WidgetLayout>][]=[["quote-library.quote-of-day","Quote of the Day","quote","The latest saved quote.",{x:1,w:4,mobileW:12,h:2,order:2}],["quote-library.pinned","Pinned Quotes","pin","Pinned saved quotes.",{x:1,w:4,mobileW:12,h:2,order:30}],["quote-library.recent","Recent Quotes","clock-3","Recently added quotes.",{x:1,w:4,mobileW:12,h:2,order:31}]];for(const [id,name,icon,description,defaultLayout] of definitions)if(!this.widgets.has(id))this.registerWidget({id,name,icon,description,defaultLayout,render:(_,container)=>render(id.endsWith("quote-of-day")?"daily":id.endsWith("pinned")?"pinned":"recent",container)});}
 private registerFallbackPrayerWidget(){const id="prayer-library/overview";if(this.widgets.has(id))return;this.registerWidget({id,name:"Prayer Library",icon:"heart",description:"Daily prayer rotation and schedules.",defaultLayout:{x:9,w:4,mobileW:12,h:2,order:32},render:(_,container)=>{const count=this.app.vault.getMarkdownFiles().filter(file=>{const meta=this.app.metadataCache.getFileCache(file)?.frontmatter??{};return meta.type==="prayer-library-item"||typeof meta.prayer_text==="string";}).length;container.createDiv({cls:"rbd-pulse-metric",text:`${count} saved prayer${count===1?"":"s"}`});container.createEl("p",{cls:"rbd-muted",text:count?"Open the Prayer Library to pray today’s rotation.":"Prayer Library is ready for entries."});const button=container.createEl("button",{text:"Open Prayer Library"});button.onclick=()=>execute(this.app,"prayer-library:open-dashboard");}});}
 async moveWidget(fromId:string,toId:string,side:"top"|"bottom"|"left"|"right"){const from=this.layout[fromId],to=this.layout[toId];if(!from||!to)return;const targetX=side==="top"||side==="bottom"?to.x:side==="left"?to.x-from.w:to.x+to.w;from.x=Math.max(1,Math.min(13-from.w,targetX));/* Horizontal moves only change the selected card's column.  Keeping its order prevents a single card from dragging an entire masonry row with it. */if(side==="top")from.order=(to.order??99)-0.25;else if(side==="bottom")from.order=(to.order??99)+0.25;await this.saveLayout();}
 async placeWidgetInColumn(id:string,column:number){const from=this.layout[id];if(!from)return;from.x=Math.max(1,Math.min(13-from.w,column));const orders=Object.values(this.layout).map(l=>l.order).filter(v=>Number.isFinite(v));from.order=(orders.length?Math.max(...orders):0)+0.25;await this.saveLayout();}
 async importLegacy(){const f=this.app.vault.getAbstractFileByPath(this.settings.legacyPath);if(!(f instanceof TFile)){new Notice(`Legacy dashboard not found: ${this.settings.legacyPath}`);return;}const text=await this.app.vault.read(f);WIDGET_ORDER.forEach((id,i)=>{if(this.layout[id]&&text.toLowerCase().includes(id.replace(/-/g," ")))this.layout[id].order=i;});await this.saveLayout();new Notice("Legacy dashboard imported; original note preserved.");}
 private async loadLayout(){const f=this.app.vault.getAbstractFileByPath(this.settings.dashboardPath);if(f instanceof TFile){const l=readManagedLayout(await this.app.vault.cachedRead(f));if(l)this.layout=sanitizeLayout(l,this.layout);}}
 private registerNativeWidgets(){const actions=this.getQuickActions();this.registerWidget({id:"quick-actions",name:"Quick Actions",icon:"zap",defaultLayout:{x:1,w:12,mobileW:12,h:1,order:0},render:(_,c)=>{const group=c.createDiv({cls:"rbd-action-grid"});actions.filter(a=>this.settings.quickActionVisibility[a.id]!==false).sort((a,b)=>(this.settings.quickActionOrder[a.id]??99)-(this.settings.quickActionOrder[b.id]??99)).forEach((action,index)=>{const style=this.settings.quickActionStyle[action.id]??(index===0?"blue":"default");const b=group.createEl("button",{text:action.name,cls:`rbd-action-button rbd-highlight-${style}`});b.onclick=()=>execute(this.app,action.command);});}});this.registerWidget({id:"modules",name:"Modules",icon:"layout-grid",defaultLayout:{x:1,w:12,mobileW:12,h:1,order:1},render:(_,c)=>{const modules=[...this.modules.values()].filter(m=>this.isModuleEnabled(m.id)).sort((a,b)=>(this.settings.moduleOrder[a.id]??a.order??99)-(this.settings.moduleOrder[b.id]??b.order??99)||a.name.localeCompare(b.name));if(!modules.length){const empty=c.createDiv({cls:"rbd-empty-state"});empty.createEl("p",{text:"No connected modules are available yet."});empty.createEl("small",{text:"Enable an add-on, then reopen or refresh this dashboard."});return;}const group=c.createDiv({cls:"rbd-module-grid"});modules.forEach(m=>{const style=this.settings.moduleStyle[m.id]??"default",b=group.createEl("button",{cls:`rbd-module-button rbd-highlight-${style}`,attr:{"aria-label":m.description?`${m.name}: ${m.description}`:m.name,"title":m.description??m.name}});if(m.icon){const icon=b.createSpan({cls:"rbd-module-icon"});try{setIcon(icon,m.icon);}catch{icon.setText("•");}}const copy=b.createSpan({cls:"rbd-module-copy"});copy.createSpan({cls:"rbd-module-label",text:m.name});if(m.description)copy.createSpan({cls:"rbd-module-description",text:m.description});b.onclick=()=>execute(this.app,m.command);});}});this.registerWidget({id:"quote-of-day",name:"Quote of the Day",icon:"quote",defaultLayout:{x:1,w:4,mobileW:12,h:2,order:2},render:(_,c)=>this.renderQuote(c)});this.listWidget("recently-changed","Recently Changed",f=>!dashboardExcluded(this.app,f),8,{x:5,w:4,order:3});this.listWidget("favorites","Favorites",f=>!dashboardExcluded(this.app,f)&&/favorite/i.test(f.path),8,{x:9,w:4,order:4});this.listWidget("active-projects","Active Projects",f=>!dashboardExcluded(this.app,f)&&/^projects\//i.test(f.path),8,{x:1,w:4,order:5});this.listWidget("recent-journal","Recent Journal",f=>!dashboardExcluded(this.app,f)&&/^journal\//i.test(f.path),7,{x:5,w:4,order:6});this.registerWidget({id:"vault-pulse",name:"Vault Pulse",icon:"activity",defaultLayout:{x:9,w:4,order:7},render:(_,c)=>{const fs=this.app.vault.getFiles(),day=Date.now()-86400000;c.createDiv({cls:"rbd-pulse-metric",text:`${fs.length} files`});c.createEl("p",{cls:"rbd-muted",text:`${new Set(fs.map(f=>f.parent?.path)).size} folders · ${fs.filter(f=>f.stat.mtime>day).length} changed today`});}});}
 private async renderQuote(c:HTMLElement){const candidates=this.app.vault.getMarkdownFiles().map(file=>({file,meta:this.app.metadataCache.getFileCache(file)?.frontmatter??{}})).filter(x=>typeof x.meta.quote_text==="string"&&!Boolean(x.meta.quote_archive));if(!candidates.length){c.createDiv({cls:"rbd-empty-state",text:"Your saved quotes will appear here."});return;}const pinned=candidates.filter(x=>x.meta.quote_pin===true||String(x.meta.quote_pin).toLowerCase()==="true"),pool=pinned.length?pinned:candidates,item=pool[Math.floor(Date.now()/86400000)%pool.length],text=String(item.meta.quote_text).replace(/^['"]|['"]$/g,"");const card=c.createDiv({cls:"rbd-quote-card rbd-quote-card-link",attr:{role:"link",tabindex:"0","aria-label":`Open quote${item.meta.quote_author?` by ${item.meta.quote_author}`:""}`}});card.createEl("blockquote",{cls:"rbd-quote-text",text});const author=String(item.meta.quote_author||"").trim(),source=String(item.meta.quote_source||"").trim();if(author||source){const footer=card.createDiv({cls:"rbd-quote-footer"});if(author)footer.createSpan({cls:"rbd-quote-author",text:`— ${author}`});if(source)footer.createSpan({cls:"rbd-quote-source",text:source});}const open=()=>{if(!this.editing)this.openNote(item.file.path);};card.onclick=open;card.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}};}
 private listWidget(id:string,name:string,filter:(f:any)=>boolean,limit:number,layout:Partial<WidgetLayout>){this.registerWidget({id,name,icon:id==="recently-changed"?"clock-3":id==="favorites"?"star":id==="active-projects"?"folder-kanban":id==="recent-journal"?"book-open":"list",defaultLayout:layout,render:(_,c)=>{const files=this.app.vault.getMarkdownFiles().filter(filter).sort((a,b)=>b.stat.mtime-a.stat.mtime).slice(0,limit);if(!files.length){c.createDiv({cls:"rbd-empty-state",text:"Nothing here yet."});return;}const list=c.createEl("ul",{cls:"rbd-link-list"});files.forEach(f=>{const li=list.createEl("li",{cls:"rbd-link-row"}),a=li.createEl("a",{text:f.basename});a.onclick=()=>this.openNote(f.path);});}});}
 private async loadMarkdownWidgets(){const files=this.app.vault.getMarkdownFiles().filter(f=>f.path.startsWith(`${this.settings.widgetFolder}/`));for(const f of files){const fm=frontmatter(await this.app.vault.cachedRead(f));if(fm.type!=="dashboard-widget"||fm.enabled===false)continue;const id=String(fm.widget_id||f.basename);this.registerWidget({id,name:String(fm.title||f.basename),defaultLayout:{w:4,order:99},render:(_,c)=>{c.createEl("p",{text:`Widget definition: ${f.basename}`});}});}}
}
