import { App, Notice, Plugin, TFile } from "obsidian";
import { DashboardView } from "./dashboard";
import { DashboardSettingsTab } from "./settings";
import { DASHBOARD_VIEW, type DashboardContext, type DashboardSettings, type DashboardWidgetDefinition, type WidgetLayout } from "./types";
import { defaultLayouts, defaultSettings, normalizeSettings, readManagedLayout, sanitizeLayout, writeLayoutNote, WIDGET_ORDER } from "./utils";
const FALLBACKS:Record<string,string>={"quote-library:open-dashboard":"quote-library-dashboard","scripture-library:open-dashboard":"scripture-library-dashboard","movie-library:open-dashboard":"movie-library-dashboard","study-planner:open-dashboard":"mens-study-planner-dashboard","mens-study-planner:open-dashboard":"mens-study-planner-dashboard","marriage-companion:open-dashboard":"marriage-companion-dashboard","vault-backup:open-dashboard":"vault-backup-dashboard","prayer-library:open-dashboard":"prayer-library-dashboard","journal-companion:open-dashboard":"journal-companion-dashboard"};
function execute(app:App,id:string){const c=(app as App&{commands?:{executeCommandById:(id:string)=>boolean}}).commands;if(c?.executeCommandById(id))return;const v=FALLBACKS[id]??id;void app.workspace.getLeaf(true).setViewState({type:v,active:true});}
function frontmatter(text:string){const out:Record<string,string|boolean>={};if(!text.startsWith("---\n"))return out;const end=text.indexOf("\n---\n",4);if(end<0)return out;for(const line of text.slice(4,end).split("\n")){const m=/^([\w-]+):\s*(.*)$/.exec(line);if(m)out[m[1]]=m[2].replace(/^['"]|['"]$/g,"");}return out;}
export default class RedBeardDashboard extends Plugin{
 settings:DashboardSettings=defaultSettings();layout:Record<string,WidgetLayout>=defaultLayouts();widgets=new Map<string,DashboardWidgetDefinition>();editing=false;private timer?:number;
 async onload(){const d=await this.loadData() as any;this.settings=normalizeSettings(d);this.layout=sanitizeLayout(d?.layout);await this.loadLayout();this.registerView(DASHBOARD_VIEW,l=>new DashboardView(l,this));this.addSettingTab(new DashboardSettingsTab(this.app,this));this.registerNativeWidgets();await this.loadMarkdownWidgets();this.addRibbonIcon("layout-dashboard","Open Red-Beard Dashboard",()=>void this.openDashboard());this.addCommand({id:"open-dashboard",name:"Open dashboard",callback:()=>void this.openDashboard()});this.addCommand({id:"edit-layout",name:"Edit dashboard layout",callback:()=>this.toggleEditor()});this.addCommand({id:"refresh",name:"Refresh dashboard",callback:()=>void this.refreshViews()});this.addCommand({id:"open-settings",name:"Open dashboard settings",callback:()=>this.openSettings()});this.addCommand({id:"import-legacy",name:"Import/re-import legacy dashboard",callback:()=>void this.importLegacy()});this.addCommand({id:"reset-layout",name:"Reset dashboard layout",callback:()=>void this.resetLayout()});if(this.settings.dashboard.autoRefreshSeconds>0)this.timer=window.setInterval(()=>void this.refreshViews(),this.settings.dashboard.autoRefreshSeconds*1000);if(this.settings.dashboard.startup)this.app.workspace.onLayoutReady(()=>void this.openDashboard());}
 onunload(){if(this.timer)window.clearInterval(this.timer);this.widgets.forEach(w=>w.cleanup?.());}
 registerWidget(def:DashboardWidgetDefinition){if(this.widgets.has(def.id))throw new Error(`Widget already registered: ${def.id}`);this.widgets.set(def.id,def);if(!this.layout[def.id])this.layout[def.id]=sanitizeLayout({[def.id]:def.defaultLayout})[def.id];void this.refreshViews();return()=>{this.widgets.delete(def.id);void this.refreshViews();};}
 layoutFor(def:DashboardWidgetDefinition){return this.layout[def.id]??defaultLayouts()[def.id]??{x:1,w:4,mobileW:12,h:1,order:99,visible:true,locked:false};}
 context():DashboardContext{return{app:this.app,vault:this.app.vault,settings:this.settings,layout:this.layout,refresh:()=>this.refreshViews(),openNote:p=>this.openNote(p),notice:m=>new Notice(m)};}
 async saveSettings(){await this.saveData({...this.settings,layout:this.layout});}
 async saveLayout(){await this.saveSettings();try{await writeLayoutNote(this.app.vault,this.settings,this.layout);}catch(e){new Notice(`Could not save layout: ${e instanceof Error?e.message:String(e)}`);}await this.refreshViews();}
 async resetLayout(){this.layout=defaultLayouts();await this.saveLayout();new Notice("Dashboard layout reset.");}
 async openDashboard(){const leaf=this.app.workspace.getLeaf(true);await leaf.setViewState({type:DASHBOARD_VIEW,active:true});this.app.workspace.revealLeaf(leaf);await this.refreshViews();}
 openNote(path:string){void this.app.workspace.openLinkText(path.replace(/\.md$/i,""),"",false);}
 openSettings(){const s=(this.app as any).setting;s?.open?.();window.setTimeout(()=>s?.openTabById?.(this.manifest.id),100);}
 toggleEditor(){this.editing=!this.editing;void this.refreshViews();}
 async refreshViews(){for(const l of this.app.workspace.getLeavesOfType(DASHBOARD_VIEW))if(l.view instanceof DashboardView)try{await(l.view as DashboardView).render();}catch(e){new Notice(`Dashboard refresh failed: ${e instanceof Error?e.message:String(e)}`);}}
 async moveWidget(fromId:string,toId:string,side:"top"|"bottom"|"left"|"right"){const from=this.layout[fromId],to=this.layout[toId];if(!from||!to)return;const ids=[...this.widgets.keys()].sort((a,b)=>(this.layout[a]?.order??99)-(this.layout[b]?.order??99));const old=ids.indexOf(fromId);if(old>=0)ids.splice(old,1);const idx=ids.indexOf(toId);ids.splice(Math.max(0,idx+(side==="bottom"?1:0)),0,fromId);ids.forEach((id,i)=>{if(this.layout[id])this.layout[id].order=i;});await this.saveLayout();}
 async importLegacy(){const f=this.app.vault.getAbstractFileByPath(this.settings.legacyPath);if(!(f instanceof TFile)){new Notice(`Legacy dashboard not found: ${this.settings.legacyPath}`);return;}const text=await this.app.vault.read(f);WIDGET_ORDER.forEach((id,i)=>{if(this.layout[id]&&text.toLowerCase().includes(id.replace(/-/g," ")))this.layout[id].order=i;});await this.saveLayout();new Notice("Legacy dashboard imported; original note preserved.");}
 private async loadLayout(){const f=this.app.vault.getAbstractFileByPath(this.settings.dashboardPath);if(f instanceof TFile){const l=readManagedLayout(await this.app.vault.cachedRead(f));if(l)this.layout=sanitizeLayout(l,this.layout);}}
 private registerNativeWidgets(){const actions:[[string,string],...Array<[string,string]>]=[["New Quote","quote-library:add-quote"],["New Scripture","scripture-library:add-passage"],["New Prayer","prayer-library:add-prayer"],["New Journal Entry","journal-companion:new-today"],["Pray Now","prayer-library:pray-now"],["New Movie","movie-library:manual-entry"],["New Interaction","shepherds-ledger:record-interaction"]];this.registerWidget({id:"quick-actions",name:"Quick Actions",defaultLayout:{x:1,w:6,mobileW:12,h:1,order:0},render:(_,c)=>{actions.forEach(([t,id])=>{const b=c.createEl("button",{text:t});b.onclick=()=>execute(this.app,id);});}});const modules:[[string,string],...Array<[string,string]>]=[["Quote Library","quote-library:open-dashboard"],["Scripture Library","scripture-library:open-dashboard"],["Movie Library","movie-library:open-dashboard"],["Study Planner","study-planner:open-dashboard"],["Family Companion","marriage-companion:open-dashboard"],["Vault Backup","vault-backup:open-dashboard"],["Prayer Library","prayer-library:open-dashboard"],["Journal Companion","journal-companion:open-dashboard"]];this.registerWidget({id:"modules",name:"Modules",defaultLayout:{x:7,w:6,mobileW:12,h:1,order:1},render:(_,c)=>{modules.forEach(([t,id])=>{const b=c.createEl("button",{text:t});b.onclick=()=>execute(this.app,id);});}});this.registerWidget({id:"quote-of-day",name:"Quote of the Day",defaultLayout:{w:4,order:2},render:(_,c)=>{c.createEl("p",{text:"A daily thought from your Quote Library."});}});this.listWidget("recently-changed","Recently Changed",()=>true,8);this.listWidget("favorites","Favorites",f=>/favorite/i.test(f.path),8);this.listWidget("active-projects","Active Projects",f=>/^projects\//i.test(f.path),8);this.listWidget("recent-journal","Recent Journal",f=>/^journal\//i.test(f.path),7);this.registerWidget({id:"vault-pulse",name:"Vault Pulse",defaultLayout:{w:4,order:7},render:(_,c)=>{const fs=this.app.vault.getFiles(),day=Date.now()-86400000;c.createEl("p",{text:`${fs.length} files · ${new Set(fs.map(f=>f.parent?.path)).size} folders · ${fs.filter(f=>f.stat.mtime>day).length} changed today`});}});}
 private listWidget(id:string,name:string,filter:(f:any)=>boolean,limit:number){this.registerWidget({id,name,defaultLayout:{w:4,order:WIDGET_ORDER.indexOf(id)},render:(_,c)=>{const list=c.createEl("ul"),files=this.app.vault.getMarkdownFiles().filter(filter).sort((a,b)=>b.stat.mtime-a.stat.mtime).slice(0,limit);if(!files.length)c.createEl("p",{text:"Nothing here yet."});files.forEach(f=>{const li=list.createEl("li"),a=li.createEl("a",{text:f.basename});a.onclick=()=>this.openNote(f.path);});}});}
 private async loadMarkdownWidgets(){const files=this.app.vault.getMarkdownFiles().filter(f=>f.path.startsWith(`${this.settings.widgetFolder}/`));for(const f of files){const fm=frontmatter(await this.app.vault.cachedRead(f));if(fm.type!=="dashboard-widget"||fm.enabled===false)continue;const id=String(fm.widget_id||f.basename);this.registerWidget({id,name:String(fm.title||f.basename),defaultLayout:{w:4,order:99},render:(_,c)=>{c.createEl("p",{text:`Widget definition: ${f.basename}`});}});}}
}
