import { App, PluginSettingTab, Setting } from "obsidian";
import type RedBeardDashboard from "./main";
import { DashboardCardManagerModal } from "./modals";
import { normalizeSettings } from "./utils";
export class DashboardSettingsTab extends PluginSettingTab{
 private orderRefreshTimer?:number;
 constructor(app:App,private plugin:RedBeardDashboard){super(app,plugin);}
 display(){const c=this.containerEl;c.empty();c.createEl("h2",{text:"Red-Beard Dashboard"});
  new Setting(c).setName("Storage").setHeading();
  this.text(c,"Root folder","Vault-relative folder for dashboard configuration.","rootFolder");this.text(c,"Layout note","Markdown note that stores widget positions.","dashboardPath");this.text(c,"Legacy dashboard path","Existing page used as the visual baseline.","legacyPath");this.text(c,"Widget definition folder","Safe Markdown widget definitions.","widgetFolder");
  new Setting(c).setName("Dashboard and appearance").setHeading();this.number(c,"Mobile breakpoint","Pixels before widgets stack.","mobileBreakpoint",320,2400);this.number(c,"Widget gap","Spacing between cards in pixels.","gap",0,64);this.number(c,"Page padding","Outer page padding in pixels.","padding",0,96);
  new Setting(c).setName("Modules").setHeading();
  c.createEl("p",{text:"Choose which registered app dashboards appear in the Modules card. Other Red-Beard add-ons can register here without changing this plugin."});
  c.createEl("p",{cls:"setting-item-description rbd-module-order-help",text:"Display position controls the left-to-right order in the Modules card. Position 1 is first. If you give a module a position already used by another module, the modules between them shift down automatically."});
  new Setting(c).setName("Quick Actions").setDesc("Choose, order, and style the shortcuts shown on the dashboard.").addButton(b=>b.setButtonText("Manage quick actions").onClick(()=>new DashboardCardManagerModal(this.app,this.plugin,"quick-actions").open()));
  new Setting(c).setName("Module presentation").setDesc("Choose, order, and style connected app launchers.").addButton(b=>b.setButtonText("Manage modules").onClick(()=>new DashboardCardManagerModal(this.app,this.plugin,"modules").open()));
  const modules=[...this.plugin.modules.values()].sort((a,b)=>(this.plugin.settings.moduleOrder[a.id]??a.order??99)-(this.plugin.settings.moduleOrder[b.id]??b.order??99)||a.name.localeCompare(b.name));
  modules.forEach((module,index)=>{const hasCustomFlavor=Object.prototype.hasOwnProperty.call(this.plugin.settings.moduleFlavor,module.id),flavor=hasCustomFlavor?this.plugin.settings.moduleFlavor[module.id]:module.description??"";const setting=new Setting(c).setName(module.name).setDesc(`${flavor||"No flavor text set."} · Display position ${index+1} of ${modules.length}`);setting.addToggle(t=>t.setValue(this.plugin.isModuleEnabled(module.id)).onChange(async enabled=>{this.plugin.settings.moduleVisibility[module.id]=enabled;await this.plugin.saveSettings();await this.plugin.refreshViews();}));setting.addText(t=>{t.setValue(String(index+1)).setPlaceholder("Position");t.inputEl.addClass("rbd-module-position-input");t.inputEl.setAttribute("aria-label",`Display position for ${module.name}`);t.onChange(async(value:string)=>{const requested=Number(value);if(!Number.isFinite(requested))return;this.setModulePosition(modules,module.id,requested);await this.plugin.saveSettings();this.scheduleOrderRefresh();});});setting.addText(t=>{t.setValue(flavor).setPlaceholder("Flavor text shown on the card");t.inputEl.addClass("rbd-module-flavor-input");t.inputEl.setAttribute("aria-label",`Flavor text for ${module.name}`);t.onChange(async(value:string)=>{this.plugin.settings.moduleFlavor[module.id]=value.trim();await this.plugin.saveSettings();await this.plugin.refreshViews();});});if(index>0)setting.addButton(b=>b.setButtonText("↑").setTooltip("Move up").onClick(async()=>{this.moveModule(modules,index,-1);await this.plugin.saveSettings();this.display();}));if(index<modules.length-1)setting.addButton(b=>b.setButtonText("↓").setTooltip("Move down").onClick(async()=>{this.moveModule(modules,index,1);await this.plugin.saveSettings();this.display();}));});
  new Setting(c).setName("Connected modules").setDesc("Refresh this list after enabling or reloading an add-on.").addButton(b=>b.setButtonText("Refresh module list").onClick(async()=>{this.plugin.ensureKnownIntegrations();this.plugin.announceReady();await this.plugin.refreshViews();this.display();}));
  new Setting(c).setName("Automation").setHeading();new Setting(c).setName("Refresh interval (seconds)").setDesc("0 disables automatic refresh.").addText(t=>t.setValue(String(this.plugin.settings.dashboard.autoRefreshSeconds)).onChange(async v=>{this.plugin.settings.dashboard.autoRefreshSeconds=Math.max(0,Number(v)||0);await this.plugin.saveSettings();}));new Setting(c).setName("Open on startup").addToggle(t=>t.setValue(this.plugin.settings.dashboard.startup).onChange(async v=>{this.plugin.settings.dashboard.startup=v;await this.plugin.saveSettings();}));new Setting(c).setName("Show unavailable widget placeholders").addToggle(t=>t.setValue(this.plugin.settings.showPlaceholders).onChange(async v=>{this.plugin.settings.showPlaceholders=v;await this.plugin.saveSettings();}));
  new Setting(c).setName("Maintenance").setHeading();new Setting(c).addButton(b=>b.setButtonText("Import/re-import legacy dashboard").onClick(()=>void this.plugin.importLegacy()));new Setting(c).addButton(b=>b.setButtonText("Reset layout").onClick(()=>void this.plugin.resetLayout()));
 }
 private text(c:HTMLElement,name:string,desc:string,key:"rootFolder"|"dashboardPath"|"legacyPath"|"widgetFolder"){new Setting(c).setName(name).setDesc(desc).addText(t=>t.setValue(this.plugin.settings[key]).onChange(async v=>{this.plugin.settings=normalizeSettings({...this.plugin.settings,[key]:v});await this.plugin.saveSettings();}));}
 private number(c:HTMLElement,name:string,desc:string,key:"mobileBreakpoint"|"gap"|"padding",min:number,max:number){new Setting(c).setName(name).setDesc(desc).addText(t=>t.setValue(String(this.plugin.settings[key])).onChange(async v=>{this.plugin.settings[key]=Math.max(min,Math.min(max,Number(v)||0));await this.plugin.saveSettings();}));}
 private setModulePosition(modules:Array<{id:string}>,id:string,requested:number){const target=modules.find(module=>module.id===id);if(!target)return;const position=Math.max(1,Math.min(modules.length,Math.round(requested)));const ordered=modules.filter(module=>module.id!==id);ordered.splice(position-1,0,target);ordered.forEach((module,index)=>this.plugin.settings.moduleOrder[module.id]=index+1);}
 private scheduleOrderRefresh(){window.clearTimeout(this.orderRefreshTimer);this.orderRefreshTimer=window.setTimeout(()=>this.display(),450);}
 private moveModule(modules:Array<{id:string}>,index:number,delta:number){const target=modules[index],other=modules[index+delta];if(!target||!other)return;const targetOrder=this.plugin.settings.moduleOrder[target.id]??index+1,otherOrder=this.plugin.settings.moduleOrder[other.id]??index+delta+1;this.plugin.settings.moduleOrder[target.id]=otherOrder;this.plugin.settings.moduleOrder[other.id]=targetOrder;}
}
