import type { TFile, Vault } from "obsidian";
import { normalizeVaultFile, normalizeVaultFolder, replaceManagedBlock } from "./foundation-vendor";
import { DEFAULT_QUICK_ACTIONS, LAYOUT_END, LAYOUT_START, type CardHighlightStyle, type DashboardSettings, type WidgetLayout } from "./types";
export const WIDGET_ORDER=["quick-actions","modules","quote-of-day","recently-changed","favorites","active-projects","recent-journal","vault-pulse"];
export function defaultSettings():DashboardSettings{const root="Dashboard";return{settingsVersion:1,rootFolder:root,folders:{records:"Records",profiles:"Profiles",archive:"Archive",reports:"Reports",backups:"Backups",widgets:"Widgets"},files:{index:"Library Index.md",summary:"Summary.md",journal:"Migration Journal.md",layout:"Layout.md"},naming:{idPrefix:"RBD",filenameTemplate:"{id} - {title}",dateFormat:"yyyy-MM-dd"},taxonomy:{categories:[],statuses:["active","archived"],archived:["archived"]},defaults:{},dashboard:{startup:false,autoRefreshSeconds:0,compact:false},migration:{sourceFolder:"",mode:"copy"},privacy:{showReminder:false},dashboardPath:`${root}/Layout.md`,legacyPath:"Dashboard.md",widgetFolder:`${root}/Widgets`,mobileBreakpoint:700,gap:16,padding:24,showPlaceholders:true,moduleVisibility:{},moduleOrder:{},moduleStyle:{},quickActionVisibility:{},quickActionOrder:Object.fromEntries(DEFAULT_QUICK_ACTIONS.map((a,i)=>[a.id,i])),quickActionStyle:{}};}
const num=(v:unknown,f:number,min:number,max:number)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
const styles=(v:unknown):Record<string,CardHighlightStyle>=>{const allowed=new Set<CardHighlightStyle>(["default","blue","red","hollow"]),out:Record<string,CardHighlightStyle>={};if(v&&typeof v==='object')for(const[id,value]of Object.entries(v as Record<string,unknown>))if(allowed.has(value as CardHighlightStyle))out[id]=value as CardHighlightStyle;return out;};
const bools=(v:unknown):Record<string,boolean>=>v&&typeof v==='object'?Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([,value])=>typeof value==='boolean').map(([id,value])=>[id,value as boolean])):{};
const orders=(v:unknown):Record<string,number>=>v&&typeof v==='object'?Object.fromEntries(Object.entries(v as Record<string,unknown>).map(([id,value])=>[id,num(value,99,0,9999)])):{};
export function normalizeSettings(raw:unknown):DashboardSettings{const d=defaultSettings(),v=(raw&&typeof raw==='object'?raw:{}) as Record<string,any>,root=normalizeVaultFolder(String(v.rootFolder??d.rootFolder),d.rootFolder),visibility=bools(v.moduleVisibility),moduleOrder=orders(v.moduleOrder),quickActionVisibility=bools(v.quickActionVisibility),quickActionOrder={...d.quickActionOrder,...orders(v.quickActionOrder)},moduleStyle=styles(v.moduleStyle),quickActionStyle=styles(v.quickActionStyle);return{...d,...v,rootFolder:root,moduleVisibility:{...visibility},moduleOrder:{...moduleOrder},moduleStyle,quickActionVisibility,quickActionOrder,quickActionStyle,dashboardPath:normalizeVaultFile(String(v.dashboardPath??`${root}/Layout.md`),`${root}/Layout.md`),legacyPath:normalizeVaultFile(String(v.legacyPath??d.legacyPath),d.legacyPath),widgetFolder:normalizeVaultFolder(String(v.widgetFolder??`${root}/Widgets`),`${root}/Widgets`),mobileBreakpoint:num(v.mobileBreakpoint,d.mobileBreakpoint,320,2400),gap:num(v.gap,d.gap,0,64),padding:num(v.padding,d.padding,0,96),showPlaceholders:v.showPlaceholders!==false,dashboard:{...d.dashboard,...(v.dashboard||{})}} as DashboardSettings;}
// The layout mirrors the Markdown homepage: actions and modules span the page,
// then the information widgets flow in three equal columns.
export function defaultLayouts():Record<string,WidgetLayout>{return Object.fromEntries(WIDGET_ORDER.map((id,i)=>{if(i<2)return[id,{x:1,w:12,mobileW:12,h:1,order:i,visible:true,locked:false}];const col=(i-2)%3;return[id,{x:col*4+1,w:4,mobileW:12,h:2,order:i,visible:true,locked:false}];}));}
export function sanitizeLayout(raw:unknown,fallback=defaultLayouts()):Record<string,WidgetLayout>{const result={...fallback};if(raw&&typeof raw==='object')for(const[id,val]of Object.entries(raw as Record<string,any>))if(val&&typeof val==='object'){const base=result[id]??{x:1,w:4,mobileW:12,h:1,order:99,visible:true,locked:false};result[id]={...base,...val,x:num(val.x,base.x,1,12),w:num(val.w,base.w,1,12),mobileW:num(val.mobileW,base.mobileW,1,12),h:num(val.h,base.h,1,8),order:num(val.order,base.order,0,9999),visible:val.visible!==false,locked:val.locked===true};}return result;}
export function readManagedLayout(text:string){const a=text.indexOf(LAYOUT_START),b=text.indexOf(LAYOUT_END,a+1);if(a<0||b<0)return null;try{return sanitizeLayout(JSON.parse(text.slice(a+LAYOUT_START.length,b).trim()));}catch{return null;}}
export function renderLayoutNote(_settings:DashboardSettings,layout:Record<string,WidgetLayout>,existing=""){const body=JSON.stringify(layout,null,2),fm=existing.startsWith("---\n")?existing.slice(0,existing.indexOf("\n---\n",4)+5):"---\ntype: red-beard-dashboard-layout\nschema_version: 1\n---\n\n",content=existing.startsWith("---\n")?existing.slice(fm.length):existing;return fm+replaceManagedBlock(content,{start:LAYOUT_START,end:LAYOUT_END},body);}
export async function ensureFolder(vault:Vault,path:string){let cur="";for(const s of normalizeVaultFolder(path,"").split("/").filter(Boolean)){cur=cur?`${cur}/${s}`:s;if(!vault.getAbstractFileByPath(cur))await vault.createFolder(cur);}}
export async function writeLayoutNote(vault:Vault,settings:DashboardSettings,layout:Record<string,WidgetLayout>){await ensureFolder(vault,settings.rootFolder);const f=vault.getAbstractFileByPath(settings.dashboardPath);if(f&&"extension"in f){await vault.process(f as TFile,c=>{const n=renderLayoutNote(settings,layout,c);return n===c?c:n;});}else if(!f)await vault.create(settings.dashboardPath,renderLayoutNote(settings,layout));}
